name: ytopt-CI
on:
  pull_request:
    types:
      - ready_for_review
      - opened
      - reopened
      - synchronize
jobs:
    test-ytopt:
        if: '! github.event.pull_request.draft'
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                python-version: ["3.10"]

        env:
            HYDRA_LAUNCHER: "fork"
            TERM: xterm-256color
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        defaults:
            run:
                shell: bash -l {0}

        steps:
        - uses: actions/checkout@v2
        - name: Setup conda - Python ${{ matrix.python-version }}
          uses: conda-incubator/setup-miniconda@v2
          with:
            activate-environment: condaenv
            miniconda-version: "latest"
            python-version: ${{ matrix.python-version }}
            channels: conda-forge
            channel-priority: flexible
            auto-update-conda: true

        - name: Install ytopt and dependencies
          run: |
            pip install mock pytest tensorflow keras
            conda install gcc mpich
            pip install ConfigSpace
            git clone https://github.com/ytopt-team/scikit-optimize.git
            cd scikit-optimize; pip install -e .; cd -
            git clone -b version1 https://github.com/ytopt-team/autotune.git
            cd autotune; pip install -e .; cd -
            pip install -e .

        - name: Test Plopper
          run: |
            cd test/benchmarks
            python test_plopper.py
            cd -

        - name: Run benchmarks
          run: |
            cd test/benchmarks
            python run_benchmarks.py
